CREATE TABLE NPTEL_COURSE_MARK_LIST(REG_NO INT NOT NULL,
    STUDENT_NAME VARCHAR(50),
    YEAR INT NOT NULL,
    SUB_CODE VARCHAR(50),
    NPTEL_COURSE_TITLE VARCHAR(200),
    NO_OF_CREDITS INT NOT NULL,
    NPTEL_MARK INT NOT NULL,
    SSN_MARK INT NOT NULL,
);

